### ISSUE TITLE
现在登录都有验证码了呢

### ISSUE THREAD

**Issue by i11for** [wkunzhi/SpiderCrackDemo#1]
你好，作者，现在天眼查登录都有验证码校验了呢，请问是如何解决的呢

**Comment by wkunzhi** [comment]
模拟滑动模块成功后，成功后接入打码平台对文字顺序验证码打码。

**Comment by i11for** [comment]
> 模拟滑动模块成功后，成功后接入打码平台对文字顺序验证码打码。

作者你好，目前运行程序来看，好像模拟滑块这一步需要人为的操作，请问你是如何解决这个问题的呢

**Comment by wkunzhi** [comment]
试过模拟人为轨迹滑动了么
