### ISSUE TITLE
对于淘宝反爬虫机制研究

### ISSUE THREAD

**Issue by MichaelTang11** [wkunzhi/SpiderCrackDemo#3]
我想请问一下，为什么selenium + webdriver已经将window.navigator.webdriver改为underfined了，但是只要代码移动鼠标或者点击图标就会无法登陆，人手工输入就可以登陆？

**Comment by wkunzhi** [comment]
你可以 在该网站测试一下是否改成功了 https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html

**Comment by MichaelTang11** [comment]
![无标题](https://user-images.githubusercontent.com/36433530/57680506-5bc3b000-7660-11e9-84f0-8f292697129b.png)
这样是不是算改成功了。。

**Comment by MichaelTang11** [comment]
options.add_experimental_option('excludeSwitches', ['enable-automation'])  
我主要是加了这一句话，让他检测不到webdriver

**Comment by wkunzhi** [comment]
https://github.com/wkunzhi/SpiderCrackDemo/blob/master/TaoBao/auto_login_pyppeteer.py

**Comment by wkunzhi** [comment]
pyppeteer简单有好用

**Comment by MichaelTang11** [comment]
哈哈哈好吧，我其实就是很好奇淘宝的检测机制，为啥pyppeteer就能通过webdriver就过不去
